import {Food} from "../model/food";
import error from "../assets/error.png";
import corn from "../assets/corn.png";
import grape from "../assets/grape.png";
import orange from "../assets/orange.png";
import raspberry from "../assets/raspberry.png";
import bell_pepper from "../assets/bell_pepper.png";
import carrot from "../assets/carrot.png";
import tomato from "../assets/tomato.png";


export const iconRegistry : Record<Food, any> = {
    [Food.EARLY_CARROT]: carrot,
    [Food.CARROT]: carrot,
    [Food.POTATO]: error,
    [Food.BEETS]: error,
    [Food.ONION]: error,
    [Food.KOHLRABI]: error,
    [Food.CHARD]: error,
    [Food.CUCUMBER]: error,
    [Food.GREEN_BEAN]: error,
    [Food.EGG_PLANT]: error,
    [Food.BELL_PEPPER]: bell_pepper,
    [Food.BROCCOLI]: error,
    [Food.ZUCCHINI]: error,
    [Food.ARTICHOKE]: error,
    [Food.RADISH]: error,
    [Food.ASPARAGUS]: error,
    [Food.NEW_POTATO]: error,
    [Food.PEAS]: error,
    [Food.SPINACH]: error,
    [Food.TURNIP]: error,
    [Food.LEEK]: error,
    [Food.CAULIFLOWER]: error,
    [Food.SWEET_POTATO]: error,
    [Food.JERUSALEM_ARTICHOKE]: error,
    [Food.RUTABAGA]: error,
    [Food.ENDIVE]: error,
    [Food.CELERY_ROOT]: error,
    [Food.CABBAGE]: error,
    [Food.KALE]: error,
    [Food.BRUSSELS_SPROUTS]: error,
    [Food.RED_CABBAGE]: error,
    [Food.SQUASH]: error,
    [Food.PUMPKIN]: error,
    [Food.BLACK_RADISH]: error,
    [Food.PARSNIP]: error,
    [Food.CELERY_BRANCH]: error,
    [Food.FENNEL]: error,
    [Food.CORN]: corn,
    [Food.ROMANESCO_CABBAGE]: error,
    [Food.LETTUCE]: error,
    [Food.BATAVIA]: error,
    [Food.CEBETTE]: error,
    [Food.MUSHROOMS]: error,
    [Food.MANGO]: error,
    [Food.LITCHI]: error,
    [Food.HAZELNUT]: error,
    [Food.PERSIMMON]: error,
    [Food.QUINCE]: error,
    [Food.CHESTNUT]: error,
    [Food.GRAPE]: grape,
    [Food.LOQUAT]: error,
    [Food.NECTARINE]: error,
    [Food.MIRABELLE_PLUM]: error,
    [Food.BLACKBERRY]: error,
    [Food.BLUEBERRY]: error,
    [Food.FIG]: error,
    [Food.MELO]: error,
    [Food.WATERMELON]: error,
    [Food.APRICOT]: error,
    [Food.PLUM]: error,
    [Food.CURRANT]: error,
    [Food.BLACKCURRANT]: error,
    [Food.RASPBERRY]: raspberry,
    [Food.CHERRIES]: error,
    [Food.PEACHES]: error,
    [Food.CLEMENTINE]: error,
    [Food.POMEGRANATE]: error,
    [Food.ORANGE]: orange,
    [Food.PINEAPPLE]: error,
    [Food.PEAR]: error,
    [Food.AVOCADO]: error,
    [Food.KIWI]: error,
    [Food.APPLE]: error,
    [Food.BANANA]: error,
    [Food.RHUBARB]: error,
    [Food.POMELO]: error,
    [Food.STRAWBERRY]: error,
    [Food.CITRON]: error,
    [Food.TOMATO]: tomato
}
